import java.util.Scanner;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author rojosewe
 * 
 */
public class E2 {

	public static void main(String... args){
		Scanner sc = new Scanner(System.in);
		E2 e2 = new E2();
		int n = Integer.parseInt(sc.nextLine());
		System.out.println(e2.solve(n));
	}

	private int solve(int n) {
		int n1 = 1;
		int n2 = 1;
		int sum = 0;
		int cur = 0;
		while(cur < n){
			cur = n1 + n2;
			if(cur % 2 == 0)
				sum += cur;
			n2 = n1;
			n1 = cur;
		}
		return sum;
	}
}
